### ISSUE TITLE
How can I combine the gym with EdgeSimPy?

### ISSUE THREAD

**Issue by bo-scnu** [EdgeSimPy/EdgeSimPy#15]
I want to train a DRL model for placement in EdgeSimPy, but the EdgeSimPy documentation does not provide details about creating a complex environment, especially regarding the relationship between Applications, Services, and Users. So,

1. How can I combine gym with EdgeSimPy? 
2. What is the relationship between Applications, Services, and Users in the context of placement simulation?

**Comment by paulosevero** [comment]
Hi @bo-scnu! I'm glad to hear you are considering using EdgeSimPy for your research.

I'll address both of your questions at once by explaining how you can model application placement in EdgeSimPy through policies utilizing AI algorithms (e.g., `gym`).

In EdgeSimPy, applications are simply groupings of services designed to represent complex application architectures (e.g., microservices). Services are the actual software entities deployed in the edge infrastructure. You can construct either monolithic applications (i.e., application objects composed of a single service each) or composite applications (application objects composed of multiple services).

You can create an EdgeSimPy dataset with multiple users, and each user accesses an application containing, for example, three services. Each user may have specific latency expectations for their application, represented in EdgeSimPy as the user's delay Service Level Agreement (SLA).

By default, an application's latency is determined by calculating the shortest network path connecting the user to each of the application's services. For instance, if you have an application `A_1` comprised of three services (`S_1`, `S_2`, and `S_3`) and accessed by a user `U_1`, EdgeSimPy will identify the shortest network path connecting `U_1 -> S_1 -> S_2 -> S_3`. It's important to note that EdgeSimPy automatically determines the optimal communication path for applications (custom routing schemes are supported, but you need to define them explicitly to the simulator). By default, you only need to specify the location where each service will be deployed—EdgeSimPy will automatically establish proper routing and provide you with the output latency for your placement.

Based on that, EdgeSimPy can simulate multiple edge placement scenarios. You could, for instance, model a composite application placement scenario. In such a context, for each application, you could aim to provision its services near each other and near the user to avoid delay SLA violations.

For implementation insights on application placement at the edge, refer to our EdgeSimPy tutorials library ([https://github.com/EdgeSimPy/edgesimpy-tutorials](https://github.com/EdgeSimPy/edgesimpy-tutorials)) and our published papers.

> A good example might be our paper titled ["Thea — a QoS, Privacy, and Power-aware Algorithm for Placing Applications on Federated Edges"](https://doi.org/10.1109/PDP59025.2023.00028). This paper primarily focuses on the placement of composite applications at the edge, considering application QoS requirements (Latency and Privacy) and the infrastructure's power consumption. You can check out the source code ([link here](https://github.com/paulosevero/thea)) to see how we made the whole simulation process (from creating the dataset to designing the placement strategies and automating the experiments).

If you examine the source code of the aforementioned paper, you'll notice that one of the evaluated strategies employs a multi-objective genetic algorithm (NSGA-II) from a Python library called [pymoo](https://pymoo.org/). You could take a similar approach to integrate source code from other AI libraries like `gym` into custom placement strategies in EdgeSimPy.

Please reach out if you have any further questions.
